### ISSUE TITLE
Loader error after upgrade from 4 to 5

### ISSUE THREAD

**Issue by jandolezaltm** [nils-hoyer/cypress-fail-on-console-error#265]
After upgrading from version 4 to 5 i'll get this error when running cypress component test of NextJS app.

I am not using any custom webpack config.

```
Error: Webpack Compilation Error
./node_modules/.pnpm/sinon@16.1.0/node_modules/sinon/lib/sinon/sandbox.js 243:34
Module parse failed: Unexpected token (243:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|             if (forceAssignment) {
|                 object[property] = value;
>             } else if (descriptor?.isOwn) {
|                 Object.defineProperty(object, property, descriptor);
|             } else {
 @ ./node_modules/.pnpm/sinon@16.1.0/node_modules/sinon/lib/sinon.js 8:16-42
 @ ./node_modules/.pnpm/cypress-fail-on-console-error@5.0.1/node_modules/cypress-fail-on-console-error/dist/index.js
 @ ./cypress/support/e2e.ts
```

```
Cypress 12.17.3
cypress-fail-on-console-error 5.0.1
NodeJS 18.16
Using PNPM v7
```

```js
import installLogsCollector from 'cypress-terminal-report/src/installLogsCollector';

installLogsCollector({
	collectTypes: [
		'cons:log',
		'cons:info',
		'cons:warn',
		'cons:error',
		'cy:log',
		'cy:xhr',
		'cy:fetch',
		'cy:request',
		'cy:intercept',
		'cy:command',
	],
});
```

cypress.config
```js
import attachTerminalReport from 'cypress-terminal-report/src/installLogsPrinter';

const setupNodeEvents: Cypress.ComponentConfigOptions['setupNodeEvents'] = (
	on,
	config,
) => {
	attachTerminalReport(on);
};

component: {
		devServer: {
			framework: 'next',
			bundler: 'webpack',
		},
		screenshotOnRunFailure: true,
		screenshotsFolder: './cypress/snapshots/actual',
		trashAssetsBeforeRuns: false,
		video: false,
                setupNodeEvents,
		viewportHeight: 1080,
		viewportWidth: 1920,
	},
```

**Comment by nils-hoyer** [comment]
Hi @jandolezaltm, could you please provide a repo to reproduce the issue?

**Comment by work933k** [comment]
I'm also running into the same issue. Unfortunatly i'm unable to provide a sample repo. I'll provide some info which might help reproduce the issue.

This is the error trace:
```
Oops...we found an error preparing this test file:

  > src/support/index.ts

The error was:

Error: Webpack Compilation Error
/__w/1/s/node_modules/sinon/lib/create-sinon-api.js 19:16
Module parse failed: Unexpected token (19:16)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  */
| module.exports = function createApi(opts = { sinonXhrLib: nise }) {
>     assert(opts?.sinonXhrLib, "No XHR lib passed in");
|     const { sinonXhrLib } = opts;
| 
 @ /__w/1/s/node_modules/sinon/lib/sinon.js 3:18-47
 @ /__w/1/s/node_modules/cypress-fail-on-console-error/dist/index.js
 @ ./src/support/index.ts
    at handle (/root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /root/.cache/Cypress/12.14.0/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:304:22
````
Cypress/webpack related dependencies:
```
"@cypress/code-coverage": "3.12.18",
"@nx/cypress": "16.3.2",
"cypress": "12.14.0",
"cypress-fail-on-console-error": "5.1.0",
"cypress-file-upload": "5.0.8",
"cypress-multi-reporters": "1.6.4",
"cypress-plugin-tab": "1.0.5",
"@nx/webpack": "16.3.2",
"@svgr/webpack": "5.5.0",
"@types/webpack-env": "1.18.2",
"babel-loader": "9.1.3",
"babel-preset-env": "1.7.0",
```
